### ISSUE TITLE
Could you tell me how to compile the source?

### ISSUE THREAD

**Issue by WoodsCheney** [aminophen/w32tex-build#1]
I want to change some code in the web2c，so I find w32tex source code.But it's diffcult to generate the exe file.
Could you give some advice,thanks.

**Comment by aminophen** [comment]
I'm on Windows 7 and 10; this is a brief translation from my own Japanese blog [here](http://d.hatena.ne.jp/acetaminophen/20160812/1470992025):

1. Obtain w32tex-src.tar.xz from http://www.tug.org/svn/texlive/trunk/Master/source/
2. Install Visual Studio (I tested with 2013 and 2010, but other versions may work), for `nmake`, `cl`, `link`, etc. Free version (named "Express", I think) is enough.
3. Install [MSYS 1](http://www.mingw.org/wiki/MSYS), for `make` etc.
4. Start "VS2013 x86 Native Tools Command Prompt" (or VS2010 ...)
5. If MSYS's `make` cannot be found from VS Command Prompt, execute the following:
    - `set PATH=%PATH%;C:\MinGW\msys\1.0\bin` (the MSYS path may depend on your env)
6. Extract w32tex-src.tar.xz to some directory, and enter there (e.g. `cd w32tex-src`)
7. `cd ktx\texk\kpathsea` then `make` (you will have kpathsea623.dll)
8. `cd win32` then `make`
9. Copy kpathsea623.dll to `ktx\texk\web2c` and to `ktx\texk\web2c\web2c`
10. `cd ktx\texk\web2c` then `make` (-> error will be thrown, like "Cannot open include file: 'cweb.h': No such file or directory)
11. `make cweb` (-> error like "cl : Command line error D8003 : missing source filename")
12. `make`

You will get `tangle.exe`, `weave.exe` , etc, and those should be what you say "web2c"

BTW,

> I want to change some code in the web2c

What change? I'm curious about that

**Comment by aminophen** [comment]
Note that the above is *not* what Akira is doing (I guess). So, there might be some incompatibility when you use such self-build binaries within TeX Live or W32TeX.

**Comment by WoodsCheney** [comment]
Thanks for your answer.I spend one week trying to compile it. But always failed.  It's diffcult to find the way on the internet. Your work is excellent and helpful. I will try your method. Thanks again. Here upon is my cordial appreciation.

**Comment by aminophen** [comment]
JFYI: the latest description https://github.com/aminophen/w32tex-build/blob/master/BUILDING.md
